version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo-data:/data/db

  nextjs:
    #build:
      #context: 
       #dockerfile: Dockerfile
    # container_name: nextjs-app
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://admin:admin123@mongo:27017/llm-monitoring?authSource=admin
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=NgmZsfLUV4Lq0itjiM8Jm7u8NG5mEE0O/M9guzDO6RM
      - NODE_ENV=development
    depends_on:
      - mongo
    restart: unless-stopped
   # volumes:
      # - .:/app
      # - /app/node_modules
      # - /app/.next

volumes:
  mongo-data:
